apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  labels:
    identifier: nodejs-pod
spec:
  containers:
    - name: node-sample
      image: bhushankumar3/kubernetes-cluster-nodejs:latest
      ports:
        - containerPort: 3000
