apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: node-sample-1
  template:
    metadata:
      labels:
        app: nodejs
        app.kubernetes.io/name: node-sample-1
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
        - name: node-sample
          image: bhushankumar3/kubernetes-cluster-nodejs:latest
          ports:
            - containerPort: 3000
