apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-nodeport
spec:
  type: NodePort
  ports:
    - port: 1020
      targetPort: 3000
      nodePort: 34567
  selector:    
    identifier: nodejs-pod
